---

- hosts: all
  become: true
  tasks:

  - name: update repository
    when: ansible_distribution in ["Alpine"]
    community.general.apk:
      update_cache: yes

  - name: install apache2 package
    community.general.apk:
      name: apache2
      state: latest

  - name: install openrc package
    community.general.apk:
      name: openrc
