---

- hosts: all
  become: true
  tasks:

  - name: update repository
    when: ansible_distribution in ["Alpine"]
    community.general.apk:
      update_cache: yes

  - name: install apache2 package
    community.general.apk:
      name: apache2
      state: latest

  - name: install openrc package
    community.general.apk:
      name: openrc

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip
 
  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: jim
      group: jim
